const translation = {
    "English": {
        "command_cheatsheet": "Commands Cheatsheet",
        "select_language": "Select Language",
        "chat_config": "Chat Config",
        "select_oai_model": "Select OAI Model",
        "select_oai_language": "Select OAI Language",
        "select_cheatsheet": "Select Cheatsheet",
        "chat_about": "Chat About",
        "ai_assistant": "AI Assistant",
        "you": "You",
        "type_your_message": "Type your message",
        "send": "Send",
    },
    "中文": {
        "command_cheatsheet": "命令查询表",
        "select_language": "选择语言",
        "chat_config": "聊天配置",
        "select_oai_model": "选择OAI模型",
        "select_oai_language": "选择OAI语言",
        "select_cheatsheet": "选择查询表",
        "chat_about": "聊天关于",
        "ai_assistant": "AI助手",
        "you": "你",
        "type_your_message": "输入你的消息",
        "send": "发送",
    },
    "繁體中文": {
        "command_cheatsheet": "命令查詢表",
        "select_language": "選擇語言",
        "chat_config": "聊天配置",
        "select_oai_model": "選擇OAI模型",
        "select_oai_language": "選擇OAI語言",
        "select_cheatsheet": "選擇查詢表",
        "chat_about": "聊天關於",
        "ai_assistant": "AI助手",
        "you": "你",
        "type_your_message": "輸入你的消息",
        "send": "發送",
    },
    "日本語": {
        "command_cheatsheet": "コマンドチートシート",
        "select_language": "言語を選択",
        "chat_config": "チャット設定",
        "select_oai_model": "OAIモデルを選択",
        "select_oai_language": "OAI言語を選択",
        "select_cheatsheet": "チートシートを選択",
        "chat_about": "チャットについて",
        "ai_assistant": "AIアシスタント",
        "you": "あなた",
        "type_your_message": "メッセージを入力",
        "send": "送信",
    }
}

window.translation = translation;