### chat settings
admin_key: f4b1a7dc92c8a576c918844f440ba90a
api_key: 0764ee6f39280e8b485e9a18668f6a62
openai_api_chat_base: http://127.0.0.1:5010/v1
openai_api_funcall_base: http://127.0.0.1:5002/v1
# openai_api_rephase_base: http://127.0.0.1:5010/v1
local_tabby_server_base: http://localhost:5555/v1
using_remoteapi: true
remoteapi_endpoint: deepseek     #openairouter,cohere, mistral, claude, xiaoai

### SD settings
SDAPI_url: http://127.0.0.1:7860
hr_upscaler: Latent (bicubic)
sampler_name: Euler a
sd_model_checkpoint: astranime_V6

### server settings
debug_mode: true
server_address: 0.0.0.0
server_port: 5500

### audio settings, only for local xtts api server existed, otherwise you can select during remote server starting
xtts_api_base: http://127.0.0.1:8020/tts_to_audio/

### sentimental settings
sentimodelpath: config/sentimodel/touch20032003_xuyuan-trial-sentiment-bert-chinese

### optinal settings
chroma_server_host: 192.168.5.179
chroma_server_http_port: 8000
yeelight_url: 192.168.5.142
