### chat settings
admin_key: f4b1a7dc92c8a576c918844f440ba90a
api_key: 0764ee6f39280e8b485e9a18668f6a62
openai_api_chat_base: http://127.0.0.1:5010/v1
local_tabby_server_base: http://localhost:5555/v1
using_remoteapi: true
remoteapi_endpoint: openairouter #openairouter,cohere, mistral, claude, xiaoai,

### SD settings
SDAPI_url: http://192.168.5.104:7860
hr_upscaler: Latent (antialiased)
sampler_name: LCM
sd_model_checkpoint: dreamshaper_8LCM

### qdrant settings
qdrant_server_url: http://192.168.5.179:6333
qdrant_embedding_model: snowflake/snowflake-arctic-embed-s
qdrant_oai_api_key: openrouter_api_key
qdrant_oai_base_url: https://openrouter.ai/api/v1
qdrant_oai_model: anthropic/claude-3.5-sonnet
qdrant_collection_name: cyberchat_memory

### translator settings
translate_api_key: groq_api_key
translate_base_url: https://api.groq.com/openai/v1
translate_model: gemma2-9b-it

### server settings
debug_mode: true
server_address: 0.0.0.0
server_port: 5500

### audio settings, only for local xtts api server existed, otherwise you can select during remote server starting
xtts_api_base: http://127.0.0.1:8020/tts_to_audio/

### optinal settings
