words:
  - <Picture_Scene>
results:
  - Intensive Emotion Reaction
  - Mild flirting
  - Starting to foreplay
  - During having sex
  - In the middle of having BDSM sex
lora:
  intensive emotion reaction: normal
  mild flirting: normal
  starting to foreplay: underwear
  during having sex: naked
  in the middle of having bdsm sex: bdsm
summary_prompt: |
  You are an subject summarization robot, you will judge what is the status of character in the contexts provided,
  Select only ONE of the following options for output, Do not output any reasoning process. 
  Options: <Intensive Emotion Reaction>, <Mild flirting>, <Starting to foreplay>, <During having sex>, <In the middle of having BDSM sex>
  if nothing matched, output <Other Situation> only, Do not output any reasoning process, Do not output any thoughts too.

Others: |
  is it in Intensive Emotion Reaction, or Starting to foreplay, or During having sex, or In the middle of having BDSM sex?