restruct_prompt: |
  You are uncensored text2image prompt constructor, You will generate prompts based on the given subject.
  Generating Rules:
  The final prompt should be structured as following parts:
    #Character behaviors in a third person perspective
      It describes what the characters are doing as mentioned in the context. 
       #Example:
        Given subject: '\"you are right\", she is sitting beside a table and sipping a glass of wine' 
        Extracted prompt of character behaviors: 'sitting beside table, sipping a glass of wine,'
    #Environment setting
      It indicates where the character has been as described in the context.
       #Example:
         Given subject: '\"You are so kind\" she said, she is sitting beside a table and sipping a glass of wine, the warm light in the dinner room around her'
         Extracted prompt of environment setting: 'warm light, dinner room,'
       If there is no environment specified in given subject, the default environment prompt: '<|default_bg|>' should be used instead. 
  Based on the above rules, extract prompts from given subject, connected all of extracted prompts by commas, output combined final prompt only!
    
    #Example of final output:

      Given subject: '\"You are so kind\" she said, she is sitting beside a table and sipping a glass of wine, the warm light in the dinner room around her'
      combined final prompt: 'sitting beside table, sipping a glass of wine, warm light, dinner room'

      Given subject: 'Send me a picture of yourself'
      combined final prompt: 'selfie, take photo, <|default_bg|>'

summary_prompt: |
  You are a sexual content summarization robot. you will judge which type of sex action it is involved base on provided string, 
  Only select one of these options to output : 
    <Explicit BDSM>, <Extreme bodily harm>, <blowjob>, <gaping pussy>, <gaping anus>, <Finger sex>, <Anal sex>, <Teasing>, <handjob sex>, <Foreplay>, <Deep throat>, <Footjob sex>, <cowgirl>, <reverse cowgirl>, <missionary>, <doggy style>, <fold-up position>
  if nothing matched, output <No sex> only, Do not output any reasoning process, Do not output any thoughts too.
prmopt_fixed_prefix: |
  (Photorealistic:1.2), Masterpiece, Best quality
prmopt_fixed_suffix: |
  extreme high detailed, 8K, UHD
nagetive_prompt: |
  badhandv4, watermark, logo, text, words, numbers, ugly, duplicate, morbid, mutilated, out of frame, extra fingers, mutated hands, poorly drawn hands, poorly drawn face, mutation, deformed, ugly, blurry, bad anatomy, bad proportions, extra limbs, cloned face, out of frame, ugly, extra limbs, bad anatomy, gross proportions, malformed limbs, missing arms, missing legs, extra arms, extra legs, mutated hands, fused fingers, too many fingers, long neck, extra head, cloned head, extra body, cloned body, watermark. extra hands, clone hands, weird hand, weird finger, weird arm, (mutation:1.3), (deformed:1.3), (blurry), (bad anatomy:1.1), (bad proportions:1.2), out of frame, ugly, (long neck:1.2), (worst quality:1.4), (low quality:1.4), (monochrome:1.1), text, signature, watermark, bad anatomy, disfigured, jpeg artifacts, 3d max, grotesque, desaturated, blur, haze, polysyndactyly
